#%RAML 1.0 DataType

type: object
properties:
  orderID: 
    type: number
    required: True
    example: 3081
  orderMessage: 
    type: string
    required: True
    example: "Order has been saved successfully in the database."
 
